#!/usr/bin/env python
import sys, os
if len(sys.argv) < 3:
    print 'Usage: python template filetype templatename'
else:
    file_type = sys.argv[1]
    template_name = sys.argv[2]
    last_line = '%%'
    ret_str = None
    filePath = os.path.split(os.path.realpath(__file__))[0] + '/'
    assert(os.path.exists(filePath + file_type))
    for line in open(filePath + file_type):
        if last_line=='%%' and (line.strip() == template_name or line.partition(' ')[0] == template_name):
            ret_str = ''
            template_argv = line.partition(' ')[2].split()
            continue
        if ret_str is not None:
            if line.strip() == '%%':
                break
            else:
                ret_str += line.rstrip()+'\n'
        if last_line == '%%' and line.strip() == '':
            last_line = '%%'
        else:
            last_line = line.strip()

    assert(ret_str is not None)
    replace_argv = sys.argv[3:]
    for i in range(len(replace_argv)):
        ret_str = ret_str.replace('{$%s}' % template_argv[i],replace_argv[i])

    if ret_str is not None:
        print ret_str.rstrip()
